version: '3.1'
services:
  webserver:
    container_name: webserver
    build: ./webserver
    restart: on-failure
    command: bash -c "service php7.3-fpm start && nginx -g \"daemon off;\""
    tty: true
    depends_on:
      - database
    volumes:
      - PROJE_DIZINI:/var/www/symfony:delegated
    ports:
      - 9999:80
      - 9998:443
    extra_hosts:
      - "symfony.prod:127.0.0.1"
      - "symfony.test:127.0.0.1"
      - "database:10.10.10.12"
    networks:
      symfony_net:
        ipv4_address: 10.10.10.11

  database:
    container_name: database
    image: mysql:8.0
    restart: on-failure
    tty: true
    ports:
      - 9997:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: MY_DATABASE_NAME
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    extra_hosts:
      - "webserver:10.10.10.11"
    networks:
      symfony_net:
        ipv4_address: 10.10.10.12

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: on-failure
    depends_on:
      - database
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - 9996:80
    networks:
      symfony_net:
        ipv4_address: 10.10.10.13

  queue:
    container_name: queue
    image: rabbitmq:3.7-management
    restart: on-failure
    tty: true
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "9995:5672"
    networks:
      symfony_net:
        ipv4_address: 10.10.10.14

networks:
  symfony_net:
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24
